version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: game_compare-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - game_compare

  backend:
    build:
      context: ./backend
    container_name: game_compare-backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - game_compare
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: game_compare-frontend
    env_file:
      - .env
    ports:
      - "90:90"
    networks:
      - game_compare

networks:
  game_compare:

volumes:
  mongodata: