version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: game_compare-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - game_compare

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: game_compare-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - game_compare
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: game_compare-frontend
    env_file:
      - .env
    ports:
      - "90:90"
    networks:
      - game_compare

networks:
  game_compare:

volumes:
  pgdata: